import { FormEvent, useState } from "react";
import type { ManagedApplication } from "../../domain/types";
import { Empty, PageIntro, Status } from "../AdminLayout";

export function ApplicationsPage({ applications, onCreate }: { applications: ManagedApplication[]; onCreate: (input: object) => Promise<void> }) {
	const [open, setOpen] = useState(false); const [pending, setPending] = useState(false);
	async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setPending(true); try { await onCreate({ clientId: data.get("clientId"), name: data.get("name"), domain: data.get("domain"), clientType: data.get("clientType"), scopes: ["openid", "profile"] }); setOpen(false); } finally { setPending(false); } }
	return <><PageIntro title="Connected applications" description="Register each trusted TechMedia or approved customer application." action={<button className="primary-action" onClick={() => setOpen(!open)}>{open ? "Close" : "Register application"}</button>}/>{open && <form className="inline-form" onSubmit={submit}><label>Client ID<input name="clientId" placeholder="techmedia-ecommerce-web" required/></label><label>Name<input name="name" placeholder="TechMedia Ecommerce" required/></label><label>Domain<input name="domain" placeholder="shop.techmedia.in" required/></label><label>Type<select name="clientType"><option value="CONFIDENTIAL_WEB">Confidential web</option><option value="PUBLIC_MOBILE">Public mobile</option><option value="PUBLIC_WEB">Public web</option></select></label><button disabled={pending}>{pending ? "Registering…" : "Register"}</button></form>}{applications.length ? <section className="card-list">{applications.map((app) => <article key={app.id}><div><strong>{app.name}</strong><span>{app.clientId}</span></div><div><span>{app.domain}</span><small>{app.clientType.replaceAll("_", " ")}</small></div><Status value={app.status}/></article>)}</section> : <Empty>No OAuth applications are registered.</Empty>}</>;
}
